# Decision Trees
### form Artificial Intelligence: A Modern Approach

## A Decision Tree
* ### Represents a function that takes a vector of attribute values and returns a “decision,” a single output value. 
 * ### We will focus on Boolean classification.
 * ### Performs a series of tests, where each node in the tree corresponds to a test.


## Example: Will Wait?
* ### You’re at a restaurant, will you wait for a table?
* ### Relevant features (These go into the input vector for each example in the sample):
    * ### Alternate: Another restaurant nearby?
    * ### Bar: Do they have a bar?
    * ### Fri/Sat: true on Fri and Sat
    * ### Hungry: Are we hungry?
    * ### Patrons: {None, Some, Full}
    * ### Price: {$, $$, $$$}
    * ### Raining: Is it raining?
    * ### Reservation: Did we make a reservation
    * ### Type: {French, Italian, Thai, or burger}
    * ### WaitEstimate: {0-10 min, 11-30, 31-60, >60}



## An example of learning a decision tree for the above problem, using a sample of labeled data
![](imgs/example_tree)
* ## Each of the features or attributes above has several different values: Bar is an attribute with the values "yes" and "no"
* ## We pick an attribute, and for each 
* ## We then assign the examples to boxes according to which value was present in their case: this is splitting
* ## Next, we take another attribute, and split the examples according to which value each of the examples had into further boxes, then do more splitting, and so on, until all the remaining boxes have either only those who waited, or those who stayed. Then we can use the tree to predict whether a person outside of our data set will stay or leave

## Some sample data. Customers, with whether or not he/she waited(goal)
![Note: the numbers refer to example number in the table shown above](imgs/decision_tree_data.png)

* ## However, the order of splitting attributes is important, splitting on one attribute first instead of another might require more tests be done to separate the examples.
* ## Below reflects a poor choice and a good choice regarding which attribute to use for splitting first: splitting on Type yields no new information, but splitting on Patrons brings us closer to separating who waits and who leaves
![](imgs/splitting.png)
Note: the numbers refer to the sample number in the table above

## So, what's the best order for splitting, then?

## Desideratum: Find the Smallest Tree
* ### Can’t crunch through 2 to the 2 to the n possible trees and see which is smallest!
* ### Use the DECISION-TREE-LEARNING algorithm.
    * ### Uses the most-important attribute: the one that makes the most difference to the 
    * ### classification of an example. 

## Testing is a recursive algorithm: after each test there is a remaining mini-tree to go through.
* ## Four cases:
    * ## The remaining examples are either all positive or negative (stop).
    * ## Some pos and neg examples: choose the best attribute left to split on.
    * ## No examples left, use plurality classification applied to parent.
    * ## No attributes left, both pos and neg examples, use plurality classification.

## Here's the algorithm in pseudocode:

![](imgs/dtalgorithm.png)

## A tree that results from the above algorithm applied to our sample data

![](imgs/tree.png)

## The Importance Function: Deciding Which Class is Most Important

## We want to maximize information gain as much as we can as we create the tree

## Entropy: a measure of teh amount of uncertainty of a random variable

* ## Expressed in bits: coin tosses
    * ## 1 bit: an answer to a yes or no question
* ## Information gain = entropy loss

## Consider sending messages between treehouses using a pluck string that, per each half a second, it's either pluck or no-pluck

![](imgs/pluck.jpg)
* ## To send a series of coin tosses, how many single pluck/no-pluck's must we send?
    * ## You tell me!
* ## To transmit a single letter of the alphabet, how many pluck/no-pluck's?
    * ## How many yes-no questions must we answer?
    * ## Use binary search for the alphabet

![](imgs/scrabble.jpg)
    
* ## The answer then is:
    $$ log_{2}(26)$$
* ## How about a poker hand taken from an infinite deck of 52 different cards? You tell me.
* ## From now on, we'll use bits instead of pluck/no-pluck's


## Entropy: 
## $$H(V) = \sum_{k} P(v_{k})log_{2}\frac{1}{P(v_{k})} = - \sum_{k} P(v_{k})log_{2}P(v_{k})$$
## where V is a random variable with values $v_{k}$ each with probability $P(v_{k})$

## Where does that probability come from: the number of times it occurs over the total nuber of occurances (if your sample has 10 in it, and 4 are orange, then the probability of orange is 0.4)


## Entropy Gain: The initial entropy - the weighted average of the entropy of the child nodes

## Suppose we decide to split on attribute $A$ (whatever that is) first. If $A$ has $d$ values $E_{1}, E_{2}, E_{d}$, then it divides the training set into $d$ subsets. 

## E.g., from the will wait problem: Type, an attribute, has 4 values: French, Thai, Burger, Italian. Thus it divides samples into 4 ($d$) subsets. 


## Each subset has $p_{k}$ positive examples and $n_{k}$ negative examples, while the total number of positive and negative examples in A is given by $p+n$. The proportion of examples in any given E compared to A is $\frac{p_{k}+n_{k}}{p+n}$. Then:

## $$Remainder(A) = \sum_{k=1}^{d}\frac{p_{k}+n_{k}}{p+n}(Entropy(E_{k}))$$


## Then the information gain from testing on A is:

## $$Gain(A) = Entropy(Parent) - Remainder(A)$$



## The Big Idea: Implement the IMPORTANCE function in terms of entropy loss/information gain. 

## Random Forests

* ## Randomly split up your training data into subsets. 
* ## Choose a subset of attributes.
* ## Train several trees using these sets.
* ## Make predictions using all of the trees, take the prediction with the highest number of votes.

![](imgs/random_forests.png)

# Let's try out a decision tree using sci-kit learn!

## Get our imports

In [1]:
import numpy as np
from sklearn import tree #see http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html


## Get our data: we'll use the iris data set for now

In [2]:
from sklearn.datasets import load_iris
data = load_iris()
X = data.data
y = data.target
print X.shape
print y.shape

(150, 4)
(150,)


## Split into training and test sets

## The reason we do this is that sometimes our classifier will fit the data so well that it reflects the ideosyncracies of our sample, and not generalize well. This is called overfitting. To get a good idea of how the classifier would do on data it hasn't seen, we reserve some data that we will not use for training and test it out on that.

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [4]:
clf = tree.DecisionTreeClassifier(criterion="entropy") #see http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

## To see how we did, test on training set

In [5]:
clf.fit(X_train, y_train)
acc_train = clf.score(X_train, y_train)
acc_test = clf.score(X_test, y_test)

print("Accuracy on training data:", acc_train)
print("Accuracy on test data:", acc_test)

('Accuracy on training data:', 1.0)
('Accuracy on test data:', 0.97999999999999998)


Try out a different min samples split and see the difference

In [6]:
clf1 = tree.DecisionTreeClassifier(criterion="entropy", min_samples_split=2)
clf2 = tree.DecisionTreeClassifier(criterion="entropy", min_samples_split=50)

clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)

acc_min_samples_split_2 = clf1.score(X_test, y_test)
acc_min_samples_split_50 = clf2.score(X_test, y_test)

print("Accuracy with min split = 2:", acc_min_samples_split_2)
print("Accuracy with min split = 50:", acc_min_samples_split_50)

('Accuracy with min split = 2:', 0.97999999999999998)
('Accuracy with min split = 50:', 0.97999999999999998)


In [7]:
tree.export_graphviz(clf, out_file='imgs/tree.dot')

! dot -Tpng imgs/tree.dot -o imgs/result.png


![](imgs/result.png)

In [8]:
my_data =  np.loadtxt('willwait_data.csv', dtype=str, delimiter=',')

#Need to convert everything to numerical values
my_data[my_data=='No'] = 0
my_data[my_data =='None'] = 0
my_data[my_data=='$'] = 0
my_data[my_data=='Mexican'] = 0
my_data[my_data=='10'] = 0

my_data[my_data=='Yes'] = 1
my_data[my_data=='Some'] = 1
my_data[my_data=='$$'] = 1
my_data[my_data=='Thai'] = 1
my_data[my_data=='30'] = 1

my_data[my_data=='Full'] = 2
my_data[my_data=='$$$'] = 2
my_data[my_data=='Burger'] = 2
my_data[my_data=='60'] = 2

my_data[my_data=='Italian'] = 3

my_data = np.delete(my_data, 0, 1) 
my_data = np.delete(my_data, 0, 0).astype('float64') 

print(my_data[:5])

[[ 0.  1.  1.  0.  1.  1.  0.  0.  1.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.  1.  0.  1.  0.  0.]
 [ 0.  1.  1.  0.  1.  0.  1.  0.  1.  1.  0.]
 [ 0.  1.  1.  0.  1.  0.  0.  0.  0.  3.  0.]
 [ 0.  1.  1.  0.  1.  1.  0.  0.  0.  1.  0.]]


In [9]:
restaurant_y = my_data[:, 0]
print(restaurant_y)

[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  1.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.
  1.  1.  1.]


In [10]:
restaurant_X = my_data[:, 1:]
print(restaurant_X[:5])

[[ 1.  1.  0.  1.  1.  0.  0.  1.  0.  0.]
 [ 1.  1.  0.  1.  0.  1.  0.  1.  0.  0.]
 [ 1.  1.  0.  1.  0.  1.  0.  1.  1.  0.]
 [ 1.  1.  0.  1.  0.  0.  0.  0.  3.  0.]
 [ 1.  1.  0.  1.  1.  0.  0.  0.  1.  0.]]


In [11]:
clfr = tree.DecisionTreeClassifier(criterion="entropy")

In [12]:
Xr_train, Xr_test, yr_train, yr_test = train_test_split(restaurant_X, restaurant_y, test_size=0.33)

In [13]:
clfr.fit(Xr_train, yr_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [14]:
accr_train = clfr.score(Xr_train, yr_train)
accr_test = clfr.score(Xr_test, yr_test)
print("Accuracy on training data:", accr_train)
print("Accuracy on test data:", accr_test)

('Accuracy on training data:', 1.0)
('Accuracy on test data:', 0.76923076923076927)


In [15]:
tree.export_graphviz(clfr, out_file='imgs/treer.dot')

! dot -Tpng imgs/treer.dot -o imgs/resultr.png

![](imgs/resultr.png)